### ISSUE TITLE
lost "libgralloc_drm_intermediates"

### ISSUE THREAD

**Issue by yang-neu** [RaspberryPiFan/device_brcm_rpi4#11]
I had another issue after "Copy armeabi-v7a as  armeabi-v8a".     #9

$ ALLOW_MISSING_DEPENDENCIES=true make ramdisk systemimage vendorimage -j16
...
FAILED: ninja: 'out/target/product/rpi3/obj/SHARED_LIBRARIES/libgralloc_drm_intermediates/export_includes', needed by 'out/target/product/rpi3/obj/EXECUTABLES/android.hardware.graphics.allocator@2.0-service.rpi3_intermediates/import_includes', missing and no known rule to make it
05:55:13 ninja failed with: exit status 1

#### failed to build some targets (4 seconds) ####

**Comment by RaspberryPiFan** [comment]
When did you sync?

**Comment by RaspberryPiFan** [comment]
Probably you need to delete the android dir and re-sync.

**Comment by yang-neu** [comment]
OK.
But my local network cannot access some direct IP linked in the Android repo. Therefore it will take time.
