### ISSUE TITLE
Issue during building.. there is no directory named "armeabi-v8a"

### ISSUE THREAD

**Issue by the-kool-sk** [RaspberryPiFan/device_brcm_rpi4#15]
ERROR:-

FAILED: ninja: 'prebuilts/ndk/current/sources/cxx-stl/llvm-libc++/libs/armeabi-v8a/libc++_static.a', needed by 'out/soong/.intermediates/external/boringssl/libcrypto/android_arm_armv8-a_cortex-a72_core_shared_com.android.conscrypt/unstripped/libcrypto.so', missing and no known rule to make it

**Comment by RaspberryPiFan** [comment]
Look at #9

**Comment by the-kool-sk** [comment]
thanks..!
