### ISSUE TITLE
missing libmesa_winsys_v3d(and libmesa_pipe_v3d)

### ISSUE THREAD

**Issue by yang-neu** [RaspberryPiFan/device_brcm_rpi4#4]
Hi RaspberryPiFan

I built this source code again in the following environment.
Another error occurred.
BTW, Could you please share your image like this. https://github.com/brobwind/pie-device-brobwind-rpi3-binary

============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=10
TARGET_PRODUCT=rpi3
TARGET_BUILD_VARIANT=eng
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm
TARGET_ARCH_VARIANT=armv7-a-neon
TARGET_CPU_VARIANT=cortex-a72
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.4.0-1092-aws-x86_64-Ubuntu-16.04.6-LTS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=QP1A.190711.020
OUT_DIR=out
============================================
[ 49% 281/568] including external/mesa3d/Android.mk ...
external/mesa3d/Android.mk:71: warning: invalid GPU driver: v3d
[ 99% 567/568] finishing build rules ...
FAILED:
external/drm_gralloc/Android.mk: error: "libgralloc_drm (SHARED_LIBRARIES android-arm) missing libmesa_winsys_v3d (STATIC_LIBRARIES android-arm)"
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
external/drm_gralloc/Android.mk: error: "libgralloc_drm (SHARED_LIBRARIES android-arm) missing libmesa_pipe_v3d (STATIC_LIBRARIES android-arm)"
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
build/make/core/main.mk:1006: error: exiting from previous errors.
23:07:41 ckati failed with: exit status 1

Even if I added the option "ALLOW_MISSING_DEPENDENCIES=true",  the compiler asserted:
FAILED: ninja: 'out/target/product/rpi3/obj/STATIC_LIBRARIES/libmesa_winsys_v3d_intermediates/export_includes', needed by 'out/target/product/rpi3/obj/SHARED_LIBRARIES/libgralloc_drm_intermediates/import_includes', missing and no known rule to make it
23:24:39 ninja failed with: exit status 1

**Comment by RaspberryPiFan** [comment]
Do you have the latest version of my repo?

**Comment by yang-neu** [comment]
> Do you have the latest version of my repo?

Yes, I synced your repo on Sunday(10/27) and reversed device/brcm/rpi3/BoardConfig.mk manually.

**Comment by RaspberryPiFan** [comment]
delete the out dir and try again

**Comment by yang-neu** [comment]
Hi RaspberryPiFan

This issue still occurred even I did "make clean."
BTW I also changed the TARGET_ARCH_VARIANT.
But instead of "armv8-a-neo", the "armv8-a" worked.

**Comment by RaspberryPiFan** [comment]
Just type `sudo rm -r out` in the android dir and restart buildinj

**Comment by smndk** [comment]
I also have the exact same problem. I have tried to build the source several times during the last week and have ended up with this error every time.

**Comment by RaspberryPiFan** [comment]
Yes, mesa 3d is being removed, just wait until I can release it.

**Comment by RaspberryPiFan** [comment]
Fixed it.

**Comment by RaspberryPiFan** [comment]
But you need to resync

**Comment by smndk** [comment]
Great. Thanks.

**Comment by bski77** [comment]
resynced today as mesa3d has been removed. This issue is closed, however I have a new issue
