### ISSUE TITLE
missing libgralloc_drm (SHARED_LIBRARIES android-arm)

### ISSUE THREAD

**Issue by bski77** [RaspberryPiFan/device_brcm_rpi4#8]
Hello RaspberryPiFan, 

I am building with a host machine using Ubuntu 18.04. 
I have tried & cannot get a past this error. It complains about mesa shared libraries being missing. 

![terminal_rpi_fail](https://user-images.githubusercontent.com/57279282/68065638-9a2e5380-fd02-11e9-9109-1f027dd7dfaf.jpg)

**Comment by RaspberryPiFan** [comment]
When did you sync?

**Comment by RaspberryPiFan** [comment]
If it was yesterday or the day before yesterday, type `export ALLOW_MISSING_DEPENCIES=true`,  delete everything in external/mesa3d and create an empty file named `Android.mk` in this folder

**Comment by botswanabub** [comment]
for me was working install mesa 19.3 drivers

**Comment by RaspberryPiFan** [comment]
You need to wait, I'm currently porting mesa3d to RaspberryPi

**Comment by bski77** [comment]
I synced yesterday 11/1. 
Ok, no problem let me know when you have ported mesa3d & I will sync again & retry. 
Thank You

**Comment by RaspberryPiFan** [comment]
Fixed.
