### ISSUE TITLE
Missing static library libc++_static.a

### ISSUE THREAD

**Issue by bski77** [RaspberryPiFan/device_brcm_rpi4#9]
re-synced today. Build dies before completion. 

FAILED: ninja: 'prebuilts/ndk/current/sources/cxx-stl/llvm-libc++/libs/armeabi-v8a/libc++_static.a', needed by 'out/soong/.intermediates/external/boringssl/libcrypto/android_arm_armv8-a_cortex-a72_core_shared_com.android.conscrypt/unstripped/libcrypto.so', missing and no known rule to make it
23:36:29 ninja failed with: exit status 1

**Comment by bski77** [comment]
says that libc++_stsatic.a is missing.... but, it is in the dir......

**Comment by RaspberryPiFan** [comment]
The directory is not even there. Copy armeabi-v7a as armeabi-v8a

**Comment by bski77** [comment]
Yes, you've correct.... I copied it over & the build succeeded. However, it does not boot. only occasional flash of the rainbow pi screen......

**Comment by yang-neu** [comment]
I have another issue after "Copy armeabi-v7a as armeabi-v8a"

FAILED: ninja: 'out/target/product/rpi3/obj/SHARED_LIBRARIES/libgralloc_drm_intermediates/export_includes', needed by 'out/target/product/rpi3/obj/EXECUTABLES/android.hardware.graphics.allocator@2.0-service.rpi3_intermediates/import_includes', missing and no known rule to make it
05:55:13 ninja failed with: exit status 1

**Comment by RaspberryPiFan** [comment]
@bski77 Try to sync again

**Comment by RaspberryPiFan** [comment]
@yang-neu Re-sync
